if [ ! -d "bin/Debug" ]; then mkdir -p "bin/Debug"; fi
if [ ! -d "obj/src" ]; then mkdir -p "obj/src"; fi
if [ ! -d "obj/Debug/src" ]; then mkdir -p "obj/Debug/src"; fi
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c main.cpp -o obj/Debug/main.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Basics.cpp -o obj/Debug/src/Basics.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Compliance.cpp -o obj/Debug/src/Compliance.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Datetime.cpp -o obj/Debug/src/Datetime.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/globals.cpp -o obj/Debug/src/globals.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Interpreter.cpp -o obj/Debug/src/Interpreter.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Item.cpp -o obj/Debug/src/Item.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Juubes.cpp -o obj/Debug/src/Juubes.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Lexer.cpp -o obj/Debug/src/Lexer.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Log.cpp -o obj/Debug/src/Log.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Opcode.cpp -o obj/Debug/src/Opcode.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Paragraph.cpp -o obj/Debug/src/Paragraph.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Parser.cpp -o obj/Debug/src/Parser.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Preprocess.cpp -o obj/Debug/src/Preprocess.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Rowitem.cpp -o obj/Debug/src/Rowitem.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Second.cpp -o obj/Debug/src/Second.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Sentence.cpp -o obj/Debug/src/Sentence.o
clang++ -Wall -fexceptions -g -std=c++17 -Og -Iinclude -c src/Third.cpp -o obj/Debug/src/Third.o
clang++  -o bin/Debug/besyqit obj/Debug/main.o obj/Debug/src/Basics.o obj/Debug/src/Compliance.o obj/Debug/src/Datetime.o obj/Debug/src/globals.o obj/Debug/src/Interpreter.o obj/Debug/src/Item.o obj/Debug/src/Juubes.o obj/Debug/src/Lexer.o obj/Debug/src/Log.o obj/Debug/src/Opcode.o obj/Debug/src/Paragraph.o obj/Debug/src/Parser.o obj/Debug/src/Preprocess.o obj/Debug/src/Rowitem.o obj/Debug/src/Second.o obj/Debug/src/Sentence.o obj/Debug/src/Third.o  -Wl,-stack_size -Wl,0x30000000 -Wl,-stack_size -Wl,0x20000000  
